Updated android latest gitlab template.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,64 +1,70 @@
-image: openjdk:8-jdk
+image: openjdk:11-jdk
 
 include:
-  - template: Code-Quality.gitlab-ci.yml
+  - template: Android.latest.gitlab-ci.yml
 
 variables:
-  ANDROID_COMPILE_SDK: "31"
-  ANDROID_BUILD_TOOLS: "31.0.0"
-  ANDROID_SDK_TOOLS:   "8092744"
+  ANDROID_COMPILE_SDK: "33"
+  ANDROID_BUILD_TOOLS: "33.0.0"
+  ANDROID_SDK_TOOLS:   "8512546"
 
+# Packages installation before running script
 before_script:
   - apt-get --quiet update --yes
   - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
-  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
-  - unzip -d android-sdk-linux android-sdk.zip
-  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
-  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
-  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
-  - export ANDROID_HOME=$PWD/android-sdk-linux
-  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
+
+  # Setup path as ANDROID_HOME for moving/exporting the downloaded sdk into it
+  - export ANDROID_HOME="${PWD}/android-home"
+  # Create a new directory at specified location
+  - install -d $ANDROID_HOME
+  # Here we are installing androidSDK tools from official source,
+  # (the key thing here is the url from where you are downloading these sdk tool for command line, so please do note this url pattern there and here as well)
+  # after that unzipping those tools and
+  # then running a series of SDK manager commands to install necessary android SDK packages that'll allow the app to build
+  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
+  # move to the archive at ANDROID_HOME
+  - pushd $ANDROID_HOME
+  - unzip -d cmdline-tools cmdline-tools.zip
+  - pushd cmdline-tools
+  # since commandline tools version 7583922 the root folder is named "cmdline-tools" so we rename it if necessary
+  - mv cmdline-tools tools || true
+  - popd
+  - popd
+  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/
+
+  # Nothing fancy here, just checking sdkManager version
+  - sdkmanager --version
+
+  # use yes to accept all licenses
+  - yes | sdkmanager --licenses || true
+  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
+  - sdkmanager "platform-tools"
+  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
+
+  # Not necessary, but just for surity
   - chmod +x ./gradlew
-  - set +o pipefail
-  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
-  - set -o pipefail
 
-stages:
-  - build
-  - test
-
+# Basic android and gradle stuff
+# Check linting
 lintDebug:
+  interruptible: true
   stage: build
   script:
     - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
 
+# Make Project
 assembleDebug:
+  interruptible: true
   stage: build
   script:
-    - touch secrets1.properties #make temp file named secrets1.properties
-    - cat $BASE_URL >> secrets1.properties # copy git variable value to secrets1.properties file
     - ./gradlew assembleDebug
-    - touch $CUSTOM_APK_FILE_NAME.apk
-    - cat app/build/outputs/apk/debug/app-debug.apk >> $CUSTOM_APK_FILE_NAME.apk
   artifacts:
     paths:
-      - app/build/outputs/apk/debug/
-      - $CUSTOM_APK_FILE_NAME.apk
+      - app/build/outputs/
 
-code_quality:
-  stage: build
-  before_script:
-    - |
-      if ! docker info &>/dev/null; then
-        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
-          export DOCKER_HOST='tcp://localhost:2375'
-        fi
-      fi
-  artifacts:
-    expose_as: 'Code Quality Report'
-    paths: [gl-code-quality-report.json]
-
+# Run all tests, if any fails, interrupt the pipeline(fail it)
 debugTests:
+  interruptible: true
   stage: test
   script:
     - ./gradlew -Pci --console=plain :app:testDebug
